Repository Raboro/Obsidian-Birthday-Tracker-Plugin, pull requests merged in 2024-09, with the labels that each got.

#16 Update birthday.ts
  src/birthday.ts
Labels: bug

#18 Auto release
  .github/workflows/release.yml
  makefile
  scripts/linter.sh
  scripts/release.sh
  scripts/validate.sh
  version-bump.mjs
Labels: enhancement

#19 replaced npm with bun
  .github/workflows/linter.yml
  .github/workflows/release.yml
  bun.lockb
  package.json
  scripts/linter.sh
  scripts/release.sh
Labels: enhancement

#23 added Dependabot
  .github/dependabot.yml
  .github/workflows/dependabot-pr.yml
Labels: enhancement

#31 added first test
  .github/workflows/ci.yml
  .github/workflows/dependabot-pr.yml
  bun.lockb
  package.json
  tests/birthday.spec.ts
Labels: test
